name: Deploy React Frontend to Azure Web App

on:
  workflow_dispatch:
  # Push trigger comentado para evitar deploy automático no primeiro commit
  # Descomente as linhas abaixo se quiser deploy automático em futuros pushes:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Create production environment file
        working-directory: ./frontend
        run: |
          echo "REACT_APP_API_URL=https://expandev-app-03.azurewebsites.net/api/v1" > .env.production
          cat .env.production

      - name: npm install, build, and test
        working-directory: ./frontend
        run: |
          npm install
          REACT_APP_API_URL=https://expandev-app-03.azurewebsites.net/api/v1 npm run build --if-present
          npm run test --if-present -- --passWithNoTests

      - name: Copy static server files
        working-directory: ./frontend
        run: |
          cp -r build/* .
          cat > package.json <<'EOF'
          {
            "name": "react-app",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "npx serve -s . -l 8080"
            },
            "dependencies": {
              "serve": "^14.2.0"
            }
          }
          EOF

      - name: Zip artifact for deployment
        working-directory: ./frontend
        run: |
          zip -r release.zip . \
            -x "*.git*" \
            -x "node_modules/*" \
            -x "src/*" \
            -x "public/*" \
            -x ".env*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: ./frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: Wait for Azure to be ready
        run: sleep 30

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-app-04'
          package: .
          startup-command: 'npm start'